# Only runs if the previous CMAKE base container building
# workflow has completed, or when a change is made to the
# ENV Dockerfile or the requirements.
name: "Build ENV base container"

on:
  workflow_run:
    workflows: ["Build CMAKE base container"]
    types: [completed]

  push:
    branches: [ spi ]
    paths:
      - 'docker/Dockerfile'
      - 'requirements.txt'

  pull_request:
    branches: [ spi ]
    paths:
      - 'docker/Dockerfile'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cryoai:spi

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}